---
name: Test-Kwalitee
version: 1.00
author: []
abstract: 'Test the quality of your distribution, automatically!'
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://onyxneon.svnrepository.com/svn/chromatic_cpan/trunk/Test-Kwalitee/
requires:
  Module::CPANTS::Analyse: 0.82
  Test::Simple: 0.47
  perl: 5.6.2
provides:
  Test::Kwalitee:
    file: lib/Test/Kwalitee.pm
    version: 1.00
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
