---
abstract: "or even within your own organization\n-- testing its Kwalitee before creating a release can help you improve your\nquality as well."
author:
  - 'chromatic <chromatic@wgz.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300032, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Kwalitee
requires:
  Module::CPANTS::Analyse: 0.82
  Test::Simple: 0.47
  perl: v5.6.2
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Test-Kwalitee
  homepage: http://metacpan.org/module/Test::Kwalitee
  repository: https://github.com/karenetheridge/Test-Kwalitee.git
version: 1.02
